baseURL = 'https://blog.vincentsloan.com'
languageCode = 'en-us'
title = "Vincent on the Internet"

[menu]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "posts"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"

[params]
author = 'Vincent'
user = "vincent"
footer = "[github](https://github.com/vincentsloan) | [linkedin](https://linkedin.com/in/vincentsloan)"

[[params.social]]
key=0
name="linkedin"
url="https://linkedin.com/in/vincentsloan"

[[params.social]]
key=1
name="github"
url="https://github.com/vincentsloan"

[[params.social]]
key=2
name="email"
url="mailto:vincentsloan@gmail.com"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4

[module]
[[module.imports]]
  path = 'github.com/goodroot/hugo-classic'
